# Syntax:
# target: dependencies
# 	command

# This target is the final compile and depends on other targets
link: build/main.o build/sys.o
	gcc build/main.o build/sys.o -o build/main

# This target compiles just main.cpp (creates an object file)
build/main.o: main.c
	gcc -c -Wall -Wextra -Wpedantic main.c -o build/main.o

# This target compiles just lib/sys.c (creates an object file)
build/sys.o: lib/sys.c
	gcc -c -Wall -Wextra -Wpedantic lib/sys.c -o build/sys.o

# Remove all built files, and re-create the bin directory
clean:
	rm -rf ./build && mkdir build

# Run the solution (FYI: we could make run dependent on link)
run:
	./build/main